// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registracio.DataContext;

namespace Registracio.DataContext.Migrations
{
    [DbContext(typeof(RegistracioApiContext))]
    [Migration("20190531001857_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Registracio.Model.Employees", b =>
                {
                    b.Property<int>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmpName")
                        .IsRequired();

                    b.HasKey("EmpID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmpID = 1,
                            EmpName = "Tony Stark"
                        },
                        new
                        {
                            EmpID = 2,
                            EmpName = "Trevo Ledrick"
                        });
                });

            modelBuilder.Entity("Registracio.Model.Items", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName");

                    b.HasKey("ItemID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            ItemName = "Milk"
                        },
                        new
                        {
                            ItemID = 2,
                            ItemName = "Cheese"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
